### ISSUE TITLE
Is there a way to pull ALL information on ALL players/matches rather than just ones that you specify?

### ISSUE THREAD

**Issue by delabere** [samgfw/hltv-api#14]
Sorry - this isn't really an issue but I couldn't find a better way to ask this question.

Great tool thank you!

**Comment by zGrav** [comment]
At the moment there is no function for that, but can be possible to implement 👍

I'll do it maybe if I have time

**Comment by zGrav** [comment]
Hey @delabere , can you specify which information you would want in concrete?

I am waiting for some info on #15
